### ISSUE TITLE
'NavigableString' object has no attribute 'text'

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/pyCEURmake#41]
'NavigableString' object has no attribute 'text'
Traceback (most recent call last):
  File "/Users/wf/Documents/pyworkspace/pyCEURmake/ceurws/volumebrowser.py", line 204, in onRefreshButtonClick
    self.updateRecentlyAddedVolume(volume,_alert,i+1,total)
  File "/Users/wf/Documents/pyworkspace/pyCEURmake/ceurws/volumebrowser.py", line 184, in updateRecentlyAddedVolume
    volume.extractValuesFromVolumePage()
  File "/Users/wf/Documents/pyworkspace/pyCEURmake/ceurws/ceur_ws.py", line 305, in extractValuesFromVolumePage
    parseDict=volumeParser.parse(self.url)
  File "/Users/wf/Documents/pyworkspace/pyCEURmake/ceurws/volumeparser.py", line 87, in parse
    if len(firstH1.contents[0].text) < 20:
  File "/Users/wf/Library/Python/3.10/lib/python/site-packages/bs4/element.py", line 916, in __getattr__
    raise AttributeError(
AttributeError: 'NavigableString' object has no attribute 'text'

**Comment by WolfgangFahl** [comment]
see https://stackoverflow.com/questions/7591535/beautifulsoup-attributeerror-navigablestring-object-has-no-attribute-name

**Comment by WolfgangFahl** [comment]
![grafik](https://user-images.githubusercontent.com/1336221/209835707-3ef0ad2d-166b-4a4b-9a14-20cb671ae484.png)
